apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: product
  namespace: dev
spec:
  interval: 1m
  releaseName: product
  chart:
    spec:
      chart: ./multi-helmchart/product/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    productService:
      nodeSelector:
        kubernetes.io/os: linux
      ports:
      - name: http
        port: 3002
        targetPort: 3002
      replicas: 1