apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: online-store-dev
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./environments/dev/
  prune: true
  wait: true
  timeout: 5m0s