apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: config
  namespace: default
spec:
  interval: 1m
  releaseName: helmchart
  chart:
    spec:
      chart: ./multi-helmchart/config
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system