apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: product
  namespace: default
spec:
  interval: 1m
  releaseName: product
  chart:
    spec:
      chart: ./multi-helmchart/product/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system