apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: store-front
  namespace: dev
spec:
  interval: 1m
  releaseName: store-front
  chart:
    spec:
      chart: ./multi-helmchart/store-front/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    storeFront:
      nodeSelector:
        kubernetes.io/os: linux
      ports:
      - port: 80
        targetPort: 8080
      replicas: 2