apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: online-store
  namespace: default
spec:
  interval: 1m
  releaseName: helmchart
  chart:
    spec:
      chart: ./multi-helmchart/store-front
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    storeFront:
      nodeSelector:
        kubernetes.io/os: linux
      ports:
      - port: 80
        targetPort: 8080
      replicas: 4